### ISSUE TITLE
Not installable on retail consoles

### ISSUE THREAD

**Issue by Retro-TBG** [TheElixZammuto/moonlight-xbox#73] opened 2023-05-02 09:16 UTC
It is impossible to download Moonlight on a retail xbox, it doesn't show in the store and there is no install button on microsoft edge. Not sure where else to report this, sorry if this is the wrong spot!

**Comment by TheElixZammuto** [comment] 2023-05-02 09:36
Duplicate of #54, can you post a screenshot there?

**Closed by TheElixZammuto** 2023-05-02 09:36 UTC
