### ISSUE TITLE
Distortion when HDR is enabled. 

### ISSUE THREAD

**Issue by jz5678910** [TheElixZammuto/moonlight-xbox#107] opened 2024-01-26 14:51 UTC
**Describe the bug**
When enabling HDR through the Moonlight options menu, the top of the screen starts out as jumping around a bit, then when navigating through the game and menus the textures start to distort and muddy. 

**To Reproduce**
1. Go to Steam option on moonlight
2. Open steam application (See error sometimes)
3. Launch a game

**Expected behavior**
A clear image that displays without distortion or discoloration and HDR functional. 

**Screenshots or Videos**
If applicable, add screenshots or video recordings to help explain your problem.
![PXL_20240126_141353671](https://github.com/TheElixZammuto/moonlight-xbox/assets/38450236/cbd04265-74cc-43c4-ab7d-1b773bb60706)

![PXL_20240126_141245601](https://github.com/TheElixZammuto/moonlight-xbox/assets/38450236/63da95b1-ccc5-4f4b-abc3-0410f121bc25)

https://github.com/TheElixZammuto/moonlight-xbox/assets/38450236/5181dbef-ab86-4bda-99e8-e936f99925cd

After posting, I wasn't able to flip the video to the proper orientation, but there is black flickering at the top of the screen. 

** Logs **
While pressing Menu + View and then "Show Logs", are there any relevant log lines?
![PXL_20240126_144425738](https://github.com/TheElixZammuto/moonlight-xbox/assets/38450236/5c3c4d1c-45dd-46e0-bd01-20176b8d50ee)

**Guest Information:**
 - Xbox Model: Xbox Series X
 - TV Resolution: 4K HDR

**Host Information**
- Operating System: Windows 11
- Host Software: Sunshine
- Monitor Resolutions: 4k HDR

**Additional context**
I tested multiple bitrates ranging from 10000 kbps to 150000 kbps. 

I tried at multiple framerates, 60/120. 

I tried both h264 and HEVC. 

Issue is not present at any point when HDR is disabled, as soon as HDR is enabled through the Moonlight menu, it distorts immediately.
 Toggling HDR in game has no effect on whether or not this occurs.

**Comment by TheElixZammuto** [comment] 2024-01-27 17:22
Any difference in logs when the color glitching occurs?

**Comment by jz5678910** [comment] 2024-01-27 18:56
> Any difference in logs when the color glitching occurs?

I'll try again tomorrow when I get home and I'll get back to you. I didn't happen to turn on logs last time.

**Comment by jz5678910** [comment] 2024-01-28 20:51
> Any difference in logs when the color glitching occurs?

![PXL_20240128_204411092 MP](https://github.com/TheElixZammuto/moonlight-xbox/assets/38450236/48b954ab-bd0e-45f4-a711-25232a977b85)

**Comment by Avsynthe** [comment] 2024-01-30 14:59
I get this exact issue WITHOUT HDR enabled. I'm streaming from a Linux box where HDR isn't even supported and this issue is brand new for me.
![P_20240130_212317](https://github.com/TheElixZammuto/moonlight-xbox/assets/102600593/99a7efae-8606-4433-8e1c-41e460ee252f)

**Comment by TheElixZammuto** [comment] 2024-01-30 19:54
I'm still trying to understand what's going on.

Quick question: How is your network from the PC to your Xbox? Wired, Wireless, via LAN or via Internet?

**Comment by jz5678910** [comment] 2024-01-30 20:09
> I'm still trying to understand what's going on since with similar resolution/fps/devices i cannot still reproduce this
> 
> Quick question: How is your network from the PC to your Xbox? Wired, Wireless, via LAN or via Internet?

Both PC and Xbox are connected to Ethernet. Anything specific you'd like me to do to test? Or any other info related to my PC?

With that said, just as reference, when streaming to my phone or my Nvidia Shield TV these artifacts are not present.

**Comment by jz5678910** [comment] 2024-01-30 20:26
I should also mention this is retail mode.

**Comment by Avsynthe** [comment] 2024-01-31 00:38
Yep, wired connection here also. I've tested with multiple resolutions and bitrates with the same issue. I've also checked my other devices like Moonlight for Android TV and the issue is not present.

**Comment by RecklessBoon** [comment] 2024-01-31 02:04
I've noticed this happens on mine when I use HEVC encoding. Swapped to H.264 and I only get the stuttering black bar at the top on and off.

**Comment by jz5678910** [comment] 2024-01-31 02:05
> I've noticed this happens on mine when I use HEVC encoding. Swapped to H.264 and I only get the stuttering black bar at the top on and off.

I wish that worked. I see the same behavior on both codecs.

**Comment by Avsynthe** [comment] 2024-01-31 21:01
The version with the issue running for me is 1.15.4.70 which seems later than the latest on this git

**Comment by TheElixZammuto** [comment] 2024-01-31 22:13
Hi,
Just FYI: Moonlight by default forces HEVC on 4K resolutions so to test H264 make sure you are using a resolution lower than 4K

I still haven't found the cause and I wasn't able to reproduce it, but meanwhile I did some refactoring by making the video pipeline more similar to the one found in moonlight-qt. If you want Dev Mode can you try this build and let me know if it makes some changes?  https://transfer.sh/slz8PigIM3/moonlight-xbox-dx_1.15.5.0_x64.msixbundle

**Comment by jz5678910** [comment] 2024-01-31 23:22
> Hi, Just FYI: Moonlight by default forces HEVC on 4K resolutions so to test H264 make sure you are using a resolution lower than 4K
> 
> I still haven't found the cause and I wasn't able to reproduce it, but meanwhile I did some refactoring by making the video pipeline more similar to the one found in moonlight-qt. If you want Dev Mode can you try this build and let me know if it makes some changes? https://transfer.sh/slz8PigIM3/moonlight-xbox-dx_1.15.5.0_x64.msixbundle

Thanks for posting a build. 
Hopefully some one can chime in. If not, I'll have to wait till retail mode to test.

**Comment by RecklessBoon** [comment] 2024-02-01 22:00
> Hi,
> Just FYI: Moonlight by default forces HEVC on 4K resolutions so to test H264 make sure you are using a resolution lower than 4K
> 
> I still haven't found the cause and I wasn't able to reproduce it, but meanwhile I did some refactoring by making the video pipeline more similar to the one found in moonlight-qt. If you want Dev Mode can you try this build and let me know if it makes some changes?  https://transfer.sh/slz8PigIM3/moonlight-xbox-dx_1.15.5.0_x64.msixbundl

I loaded this with the normal dependencies. It was contrained to 1920x1080 client size despite having the desktop resolution set to 4K + HDR. Also, the distortion and black bar were still present and the color was still washed out (looked like SDR viewing HDR). 

I'll try to get some logs sometime soon. I am a programmer myself, but I have no experience with xbox dev nor C++ itself either. It might take me a hot minute to gather those. If you have pointers/links on how or where to get those while running in devkit mode, I'd be happy to try.

1080p with H.264 seems to still work mostly for me. Seems like maybe the lag was a little less in this build. I'll keep testing it out a bit more.

**Comment by RecklessBoon** [comment] 2024-02-02 01:36
> Hi,
> Just FYI: Moonlight by default forces HEVC on 4K resolutions so to test H264 make sure you are using a resolution lower than 4K
> 
> I still haven't found the cause and I wasn't able to reproduce it, but meanwhile I did some refactoring by making the video pipeline more similar to the one found in moonlight-qt. If you want Dev Mode can you try this build and let me know if it makes some changes?  https://transfer.sh/slz8PigIM3/moonlight-xbox-dx_1.15.5.0_x64.msixbundl

I loaded this with the normal dependencies. It was contrained to 1920x1080 client size despite having the desktop resolution set to 4K + HDR. Also, the distortion and black bar were still present ~~and the color was still washed out (looked like SDR viewing HDR). ~~

I'll try to get some logs sometime soon. I am a programmer myself, but I have no experience with xbox dev nor C++ itself either. It might take me a hot minute to gather those. If you have pointers/links on how or where to get those while running in devkit mode, I'd be happy to try.

1080p with H.264 seems to still work mostly for me. Seems like maybe the lag was a little less in this build. I'll keep testing it out a bit more.

For the following tests, I removed my second monitor. Also I fixed my TV settings to expect HDR content rather than the detection mode it has.

Resolution: 1920x1080
FPS: 60
Audio: Stereo
Codec: H.264
HDR: Yes
Works and looks perfectly 👍👍

I'll continue to ramp up my settings to see where the artifacting occurs.

**Comment by RecklessBoon** [comment] 2024-02-02 15:05
I've updated my findings in my previous comment (using retail version). I tested the 1.15.5 version on dev but the video didn't work and was only gray (no logs nor stats even). Sometimes I would get this error
![20240202_090517.jpg](https://github.com/TheElixZammuto/moonlight-xbox/assets/16234384/725d063a-eb70-40b9-8719-d5c25ce65a15)

**Comment by Avsynthe** [comment] 2024-02-03 09:57
After dropping the resolution to 1080p and using h264 there I can confirm the issue is gone. I hadn't realised 4k forces h265. Haven't tested 1440 yet. Will that allow h264?

**Comment by TheElixZammuto** [comment] 2024-02-03 16:57
I was finally able to reproduce it, for future reference I've used AirGPU Nvidia A10G with F1 23. 

H264 with 2160p resolution just simply crash when the limitation to force HEVC is removed.
It seems specific to 4K HEVC on Nvidia GPUs, but the problem seems to lie in the custom texture for video decoding that we provide to FFMPEG, just simply removing get_format does do the trick.

Let me know if it works so I can upload this release https://transfer.sh/5UYwCxBf4J/moonlight-xbox-dx_1.15.6.0_x64.msixbundle

**Comment by jz5678910** [comment] 2024-02-03 17:35
> I was finally able to reproduce it, for future reference I've used AirGPU Nvidia A10G with F1 23.
> 
> H264 with 2160p resolution just simply crash when the limitation to force HEVC is removed. It seems specific to 4K HEVC on Nvidia GPUs, but the problem seems to lie in the custom texture for video decoding that we provide to FFMPEG, just simply removing get_format does do the trick.
> 
> Let me know if it works so I can upload this release https://transfer.sh/5UYwCxBf4J/moonlight-xbox-dx_1.15.6.0_x64.msixbundle

Thanks again for a new build, maybe @RecklessBoon can chime in? Again, unfortunately I don't have access to Dev mode, so I'll have to wait till retail. 

Just got reference, I have a 3080 ti. Both cards are Ampere Architecture so curious if it's anything to do with that.

**Comment by RecklessBoon** [comment] 2024-02-03 17:47
Yep I'll load that and give it a try later today 👍

**Comment by gauvinc0953** [comment] 2024-02-03 18:34
I just side loaded it onto my xbox and it seems to work as intended now, no more bar at the top or discoloration happening from my limited testing.  Tried three different games from different launchers and correctly received an HDR signal with settings of 4k HDR 120hz 5.1 surround.  Switching back to retail mode I immediately encountered all the issues again.

**Comment by TheElixZammuto** [comment] 2024-02-03 18:35
@gauvinc0953 Haven't published on retail yet, so working as intended 🥳

**Comment by RecklessBoon** [comment] 2024-02-03 19:00
Can also confirm that 1.15.6 fixes all the distortion and black bar issues. TV is still reporting 60 fps while using HDR 10, but that should probably be treated as a different issue to fix in another version 👍

**Comment by TheElixZammuto** [comment] 2024-02-04 13:20
Version 1.15.6 with this fix is now pending certification in the MS Store, it should be available to you in the following hours

> Can also confirm that 1.15.6 fixes all the distortion and black bar issues. TV is still reporting 60 fps while using HDR 10, but that should probably be treated as a different issue to fix in another version 👍

Yup, feel free to open another issue for that while I'm closing this one

**Closed by TheElixZammuto** 2024-02-04 13:20 UTC
Labels: bug, resolved

**Comment by TheElixZammuto** [comment] 2024-02-04 20:13
Pushed version 1.15.7 that should fix the connection (#108) . It _might_ cause regressions in issue #107 but shouldn't be. Let me know and thank you for the patience!

**Comment by jz5678910** [comment] 2024-02-04 20:17
> Pushed version 1.15.7 that should fix the connection (#108) . It _might_ cause regressions in issue #107 but shouldn't be. Let me know and thank you for the patience!

Will do, I'll be on the lookout and will report back. Thank YOU for the quick builds.

**Comment by jz5678910** [comment] 2024-02-04 21:42
> Pushed version 1.15.7 that should fix the connection (#108) . It _might_ cause regressions in issue #107 but shouldn't be. Let me know and thank you for the patience!

@TheElixZammuto This new build fixed it! Not seeing the distortion either, so as of now haven't seen any regression. Thanks!
