### ISSUE TITLE
High Latency 60fps option. 

### ISSUE THREAD

**Issue by Tyrielwood** [TheElixZammuto/moonlight-xbox#28] opened 2022-04-04 14:31 UTC
**Describe the bug**
Firstly congrats on the app, it's amazing to be able to use my Xbox series x to stream games from my pc!! So far playing at 30 fps in the moonlight options is giving a great experience, with very few crashes. 
Unfortunately, I'm having a lot of issues with the 60fps option, making it completely unplayable, where the input latency from the controller arrives also at something like 1/2 seconds from the actual input. 
at 30 fps, I'm using a 20k bitrate at 1080p, and the latency is perfect ( better than steamlink with another pc ), 
at 60 fps the problem tho persist no matter of the resolution or bitrate. I tried as low as 720p 4k bitrate. Also important to notice that the stream itself runs very smooth, it seems to be just an input latency issue.

**To Reproduce**
1. Go to Settings
2. Click on 60FPS
3. Input Latency during Gameplay

**Expected behavior**
Input Latency around 1/2 seconds. 

**Guest Information:**
 - Xbox Model: Xbox Series S
 - TV Resolution: 4K

**Host Information**
- Operating System: Windows
- Host Software: GeForce Experience
- Monitor Resolutions: 1080p

**Additional context**
Xbox series X and PC both connected via LAN

**Comment by clint9smith** [comment] 2022-04-10 01:39
I am having the exact same experience as what is described above. In addition, the 60 FPS mode has more frequent crashes and I can't disconnect the stream without forcing the app to quit and reopening.

**Comment by blitz2kx** [comment] 2022-04-10 20:58
Raises hand..

Experiencing same on latest build on series x

**Comment by 3ap** [comment] 2022-04-25 11:15
+1, can't play even in puzzle games with such a high input lag, have to switch to 30 fps.

@TheElixZammuto do you experience the same problem with high latency in 60 fps mode? Do you have any thoughts about the reason of this behavior? Could it be fixed, do you need extra logs or something?

**Comment by TheElixZammuto** [comment] 2022-04-25 15:01
Personally I didn't, but non-reproducible issues are not news to me with this software xD

Btw the only possible explanation can be traced to https://github.com/TheElixZammuto/moonlight-xbox/commit/7a1b9f1cf7c221f76587ab2342d780d9dace2e41#diff-a052f291541975de571da39c051e42a830e5ef2fb9c0fae24df05eeb68df4a56R61

Probably 16ms are not enough for texture acquision and the app is now waiting an entire frame to make it work again.

Probably setting that timeout to a larger but not infinite amount (maybe 50-100ms) can make it work?

In this period I don't have access to my Xbox, so if someone can check it out it would be wonderful

**Comment by Nun-z** [comment] 2022-05-05 04:23
If anyone wants to test, I have created versions with the change that TheElixZammuto mentioned.

Here's a version with 25 miliseconds: https://mega.nz/file/OBxSlK6K#chS2vXhMmnOSoQIAm6-v6YTjZ10TlhBZK3H1sQuFI8A
Here's a version with 50 miliseconds: https://mega.nz/file/zQIA3JBD#yD7Ysnvvy6LugR5ruMD_jdOM_r4y3MDNhy4hMujXNTw
Here's a version with 75 miliseconds: https://mega.nz/file/vcZFCDDS#qGSeIllpHUioOnnC8zf0LhW678mwuNbWi3QvLkEtUwE
Here's a version with 100 miliseconds: https://mega.nz/file/vJRAyD4Y#vGvIS3s5RMu3EMIwhiwFHAyovMCW_nKP0IWQ77Y95Wk

**Comment by blitz2kx** [comment] 2022-05-11 12:11
> If anyone wants to test, I have created versions with the change that TheElixZammuto mentioned.
> 
> Here's a version with 25 miliseconds: https://mega.nz/file/OBxSlK6K#chS2vXhMmnOSoQIAm6-v6YTjZ10TlhBZK3H1sQuFI8A Here's a version with 50 miliseconds: https://mega.nz/file/zQIA3JBD#yD7Ysnvvy6LugR5ruMD_jdOM_r4y3MDNhy4hMujXNTw Here's a version with 75 miliseconds: https://mega.nz/file/vcZFCDDS#qGSeIllpHUioOnnC8zf0LhW678mwuNbWi3QvLkEtUwE Here's a version with 100 miliseconds: https://mega.nz/file/vJRAyD4Y#vGvIS3s5RMu3EMIwhiwFHAyovMCW_nKP0IWQ77Y95Wk

Been busy and haven't had a chance, but I will do some testing with this and report back

**Comment by Tyrielwood** [comment] 2022-05-12 09:14
unfortunately I'm running it on consumer mode, so I have no idea on how to load them without passing through the store

**Comment by Nun-z** [comment] 2022-05-19 06:44
Cutting the milliseconds in half substantially improves the latency at 60 fps.

**Comment by TheElixZammuto** [comment] 2022-05-19 20:36
I have refactored the renderer, using a frame pull approach instead of a push one. This eliminates all the multithread code and simplifies the implementation.

It's still a bit glitchy, so a couple tries would be needed to make the connection work, but I would like to have some early feedback on this, thank you!

https://github.com/TheElixZammuto/moonlight-xbox/suites/6582126521/artifacts/246693976

**Comment by TheElixZammuto** [comment] 2022-05-23 07:10
Any changes with version 1.9.0? (It's already on the MS Store)

**Comment by TheElixZammuto** [comment] 2022-05-26 15:36
Given that multiple sources confirmed to me that latency should be fixed I'm closing this. Feel free to reopen it if necessary

**Closed by TheElixZammuto** 2022-05-26 15:36 UTC
