### ISSUE TITLE
1080p does not work on Xbox Series S|X

### ISSUE THREAD

**Issue by Warlord1981** [TheElixZammuto/moonlight-xbox#11] opened 2022-01-02 18:39 UTC
Dear @TheElixZammuto thanks for your work and happy new year!
I managed to install (incl. dependencies) and run the app, however connection works only when moonlight on my xbox series X is set to 720p and not on 1080p. Even if i lower bitrate to 2000 and fps to 30. 
Runs smooth (with a little stuttering every now and then) at 720p but as soon as i enable 1080p the app just throws me to dev dashboard screen, without losing connection.
I have gigabit eth connection to both my pc & xbox.

**Comment by TheElixZammuto** [comment] 2022-01-03 09:13
Hi, 
Personally I haven't managed to reproduce the issue on My Xbox One (the 2013 VCR one), so if you are able to provide a crash dump on dev mode and then send it to me I would defintelty check this out!

**Comment by Stromduster** [comment] 2022-01-08 09:27
Hi, 
I've got the exact same issue as @Warlord1981. @TheElixZammuto, if it's useful to you, I've taken a crash dump on my Xbox Series X with last version (1.8.5.0). However, I've got trouble uploading in attachment to this comment...Please tell me how to send it to you.
And thanks in advance for your hard work !

**Comment by TheElixZammuto** [comment] 2022-01-08 10:13
@Stromduster managed to download that, thank you!

**Comment by TheElixZammuto** [comment] 2022-01-12 20:59
Yup, I managed to find what the issue is and it's connected to the "infamous" (for me) frame pacer implementation. Interestingly I did some changes to fix #2 that can improve this too, but I'm not entierely sure. If someone can test version 1.8.8 it would be very helpful, thank you!

**Comment by Stromduster** [comment] 2022-01-12 21:42
@TheElixZammuto, I just tried the new 1.8.8, and it's also crashing when setting 1080p...I'll add a crash dump in attachment.

https://drive.google.com/file/d/1vfz2GQYj15WzkyUlZjy3kG3-RBxxLOLs/view?usp=sharing

**Comment by TheElixZammuto** [comment] 2022-01-17 20:12
So it seems that the Crash Dump does not indicate the exact problem. Something else I have tried is to make sure the texture is copied correctly if one of the two is too large of another. New build is here: https://github.com/TheElixZammuto/moonlight-xbox/suites/4943163557/artifacts/143172848

**Comment by Stromduster** [comment] 2022-01-17 21:02
It's far better :). Now I can play smottly in 1080p 60 fps, when a bandwidth of 50000 Mbps without any issue (except maybe some lag the first time I streamed Steam in Big Picture, but then nothing out of the ordinary). Thanks à lot @TheElixZammuto !
Please tell us when you publish a version including this correction in the Store :).

**Comment by TheElixZammuto** [comment] 2022-01-17 21:05
So can you confirm that now 1080p on Xbox Series X works as intended?

**Comment by Stromduster** [comment] 2022-01-17 21:15
Yes, it's working fine now.

**Comment by TheElixZammuto** [comment] 2022-01-17 21:19
Wonderful, closing issue and making a new release!

**Closed by TheElixZammuto** 2022-01-17 21:19 UTC
Labels: bug
