### ISSUE TITLE
No video on Xbox Series X|S consoles

### ISSUE THREAD

**Issue by Nun-z** [TheElixZammuto/moonlight-xbox#1] opened 2021-08-05 21:35 UTC
I realize that this is a pre-release, but I just wanted to point this out in case you were not aware of it.  While testing this app on dev mode on an Xbox Series X, the video stream is never displayed.  The last text message displayed onscreen is "received first video packet after 100 ms," and then it freezes and never proceeds past that point.

See this screenshot: https://i.imgur.com/M49peIb.jpg

I'm not testing with both devices on the same network, so that could be the culprit.  I've confirmed that streaming from the server works with the official Windows version of the Moonlight client, but it does not work on PC with your UWP version or on Xbox.  I've tested it built from source (release and debug), as well as from the provided release packages, and I made sure to include the dependency, but I've never been able to get the stream to display.

What works so far for me is connecting to the remote server and displaying the list of apps.

**Comment by TheElixZammuto** [comment] 2021-08-06 07:24
I have two ideas on how this could be caused:

1) The host and the protocol

I assume that you are using the latest version of Geforce Experience to test this. Unfortunately, I don't have an nvidia card and I used https://github.com/loki-47-6F-64/sunshine for testing. If you can test on Sunshine and video does work there, I guess the problem is caused by a very old version of moonlight-common-c that was bundled with moonlight-embedded.

2) DirectX/FFMPEG

I developed and tested on OG Xbox One. If there are no API differences between Series and One in theory it should work the same way. 

If you can attach a debugger and set a breakpoint on FFmpegDecoder.cpp on line 148,205 and 219, and all 3 breakpoints are called on each frame, we can think of a Rendering Problem, otherwise is a Decoding one.

Since Rumble events are sent during the connection, in theory connection to the host is done correctly

**Comment by TheElixZammuto** [comment] 2021-08-06 13:21
Update: I have tested the App over a remote connection between two PCs (also Sunshine as a Host) and it does work, so we can exclude the connection as an issue

**Comment by Nun-z** [comment] 2021-08-06 21:42
I'm receiving another error when using Sunshine, and it still freezes and never displays the video stream.  See this screenshot: https://i.imgur.com/dnrrSgL.jpg

After placing the breakpoints and testing with Sunshine, the first breakpoint triggers, and the second and third breakpoints are then triggered in order.  This repeats itself infinitely.

When testing on Geforce Experience, the three breakpoints are triggered repeatedly in order.  The following text is displayed on the screen: https://i.imgur.com/HLgwSgZ.jpg

**Comment by TheElixZammuto** [comment] 2021-08-07 08:57
If you have a way to send me your email address I'll send you the zip folder via WeTransfer

The errors in the logs are given because the breakpoints causes mis-syncronizations between client and server, so I would not bother them too much.

While breakpoints are triggred in order, and it should be a good news, I noticed that the decoding can fail without giving error and keep going (without screen) if D3D11VA is enabled. I'll add a software encoder option in Moonlight to avoid these types of errors and to discriminate Decoding Errors from Rendering Ones

**Comment by TheElixZammuto** [comment] 2021-08-07 14:17
I have added the checkbox to enable Software Encoder, it would be interesting if something has changed depending if D3D11VA is used or not

**Comment by Nun-z** [comment] 2021-08-07 21:47
Unfortunately, I have not seen a difference with Sunshine or with Geforce Experience on my end with the checkbox added.  The video stream is still not displayed with or without the box checked.  Here's a temporary email address: noneteam826562.testinator.com

**Comment by TheElixZammuto** [comment] 2021-08-08 08:47
I'm sending you the VCPKG as we speak.

Meanwhile we could check some issue on DirectX side by attaching the debugger and reading the "Output" tab in Visual Studio. DirectX is configured in Debug Builds to output warnings on console in case of bugs or misconfigurations

**Comment by TheElixZammuto** [comment] 2021-08-09 18:04
I have updated the version to https://github.com/TheElixZammuto/moonlight-xbox/releases/tag/1.2.0, this should not fix the issue, but it includes better FFMPEG logging and DirectX, so the part which i think is crashing should log at least (hopefully)

**Comment by Nun-z** [comment] 2021-08-10 22:11
For some reason, the VCPKG email didn't come through.  Here's another temporary email address to try: testingxboxmoonlight@gmail.com.  I ran the app with Sunshine and Geforce Experience, both with and without software encoding enabled.  Here are the logs from Visual Studio: 

Geforce Experience without software encoding: https://gist.github.com/Nun-z/d468a869bc7da9fdd72e9a83583f49c9
Geforce Experience with software encoding: https://gist.github.com/Nun-z/d176093da79692f042a26b5f62e567bf
Sunshine without software encoding: https://gist.github.com/Nun-z/321bbc1ab725bdddceb49b15fcf72a33
Sunshine with software encoding: https://gist.github.com/Nun-z/398a93a717d106734e32f62cbbb19602

**Comment by TheElixZammuto** [comment] 2021-08-11 15:56
I sent you the vcpkg.zip on the gmail you gave me

As for software encoding, I can confirm at the moment is completely broken. 

Meanwhile I discovered that sometimes, on peculiar network conditions (like over a VPN) there a chance the issue you submitted is triggered, so at least I can setup a way to check it for myself

**Comment by TheElixZammuto** [comment] 2021-08-17 16:38
I have tested some more, and it seems at least for me that Wireguard can cause this issue over a VPN (but since I also had problems with Moonlight-QT the issue is probably not the same)

I also pushed this version: https://github.com/TheElixZammuto/moonlight-xbox/releases/tag/1.2.0-no-video that should have more logging, updated dependencies, also some optimitazions for remote streaming enabled and the removal of the frame pacer that can interfere with rendering

**Comment by Nun-z** [comment] 2021-08-18 05:35
After this update, it's not building for me.  Specifically, the moonlight-common-c project doesn't build.  I'm using Visual Studio Code to build moonlight-common-c with the VS 2019 amd64 kit, but once I open the project in the build directory with Visual Studio, I get the following errors: "invalid argument '/Wextra' '/Wno-unused-parameter' '/Werror.'"  If I remove those command-line arguments, I get 3060 syntax errors when trying to build it.

**Comment by Nun-z** [comment] 2021-08-19 04:07
Unfortunately, I'm not getting any video with the .msixbundle.  Here's what I get when using GeForce Experience: https://i.imgur.com/M3NS8Ib.jpg.  Here's what I get with Sunshine: https://i.imgur.com/Q6pJYa3.jpg.

**Comment by TheElixZammuto** [comment] 2021-08-19 08:09
> After this update, it's not building for me. Specifically, the moonlight-common-c project doesn't build. I'm using Visual Studio Code to build moonlight-common-c with the VS 2019 amd64 kit, but once I open the project in the build directory with Visual Studio, I get the following errors: "invalid argument '/Wextra' '/Wno-unused-parameter' '/Werror.'" If I remove those command-line arguments, I get syntax errors when trying to build it.
> 
> I'll test tomorrow with the released .msixbundle file to see if I get video.

This can be caused by CMAKE not detecting the MSVC compiler in your system. Have you tried running the bat file inside "x64 Native Tools Command Prompt for VS 2019" before opening the IDE? 



> Unfortunately, I'm not getting any video with the .msixbundle. Here's what I get when using GeForce Experience: https://i.imgur.com/M3NS8Ib.jpg. Here's what I get with Sunshine: https://i.imgur.com/Q6pJYa3.jpg.

GFE is strangely not giving any URL information from the stream, that's why it crashed (I have to check with the moonlight-common-c library), Sunshine is giving you the correct stream and it seems that decoding is doing correctly with no errors. Since other people had this issue and everyone was using Xbox Series Console, I think my rendering code is not working on Xbox Series Console (while, at least for me, is working on Xbox One)

**Comment by Nun-z** [comment] 2021-08-19 20:31
That's a shame.  Hopefully it gets ironed out.  Having Moonlight on Series consoles would be a gamechanger.

**Comment by TheElixZammuto** [comment] 2021-08-21 14:30
Meanwhile I commited some changes that disables Moonlight client connection and only does DirectX rendering (and over Discord they confirmed me that video is still not working on Series X). 

The app now should (after pressing the "Open" button without any other action inside the menu) just display many vertical pink lines of different brightness 

If you can it would be very helpful if you run the last changes with the Debug configuration and through a Debugger, and giving me what do you see and the output logs. This way if DirectX has an undefined behavior it should be printed by the debugger.

**Comment by Nun-z** [comment] 2021-08-21 22:59
I could easily be doing something wrong when compiling, but I'm not getting much of anything from debugging.  The screen displays the message "Got status 0 from Moonlight" twice, and then nothing further happens.  I'm using the vcpkg package you sent me.  This happens with both Geforce Experience and Sunshine.  Here's an image of what is on the screen: https://i.imgur.com/e6KfoTW.jpg.  Here's the output log:  https://gist.github.com/Nun-z/f0046e7509ee07cf6a94fec8a55fa1c9.

**Comment by Nun-z** [comment] 2021-08-21 23:27
Please disregard the message here that I just deleted, as I misunderstood what you wanted me to do.  After just pressing the Open button, a blue unchanging screen is displayed.  Here is an image of what is on the screen: https://i.imgur.com/9KvRoWn.jpg.  Here's the output log: https://gist.github.com/Nun-z/f4f495d1c1657e98ecc365ad24bf4ac1.

**Comment by Nun-z** [comment] 2021-08-29 04:04
With the most recent update, after selecting the open button with the debug configuration, I'm getting a purple gradient screen with the following text: 

"Started with creation of DXView"
"Got generate error from Test Logging: 80070005"
"Loading Complete"
"Rendered First Frame"

Here's an image of what's on the screen: https://i.imgur.com/fw0rnEP.jpg
Here's the debug output: https://gist.github.com/Nun-z/39369c745100e95fd04b77424d909730

**Comment by TheElixZammuto** [comment] 2021-08-29 10:28
Fortunately, this is the correct behavior of the app (which on that commit had the streaming part disabled). I updated the repo and now you should (hopefully) be able to stream properly

**Comment by Nun-z** [comment] 2021-08-30 04:40
I can confirm that streaming is working properly.

**Comment by TheElixZammuto** [comment] 2021-08-30 07:07
Perfect, closing the issue

**Closed by TheElixZammuto** 2021-08-30 07:07 UTC
