### ISSUE TITLE
Gamepad inputs breaking

### ISSUE THREAD

**Issue by blitz2kx** [TheElixZammuto/moonlight-xbox#72] opened 2023-04-28 20:49 UTC
Kind of a weird issue....

Host: PC with latest Nvidia drivers
Client: Xbox one X
Controller: Xbox one X (revision 2 with bt/latest firmware)

After connecting to the host, everything works fine until I get in game. Once game is running controller inputs start failing, and almost looks like host is recognizing keyboard.

Right analogue stick continues to work, face buttons fail, left analogue stick works intermittently.

Tried multiple title's, mouse mode works fine. On the UI of some games it seems to keep jumping to keyboard overlay commands when playing. Moonlight port worked fine, this issue is new. Makes games unplayable.

**Comment by TheElixZammuto** [comment] 2023-04-29 11:42
Closing this since it's a duplicate of #68

**Closed by TheElixZammuto** 2023-04-29 11:42 UTC
Labels: duplicate

**Comment by doytrack** [comment] 2023-06-05 04:52
In my xbox one console this error continues happen, don't matters what i do, i play too much today but this time to now i can't play because of this error (i'm brazilian forget my english's errors)
