### ISSUE TITLE
@TheElixZammuto The New retail build 1.15.6.70 is crashing every time I try to select a game from the menu. By crashing I mean it's going back to the Xbox home screen. No error or message of any kind. It gets hung on "Initializing" and then crashes.

### ISSUE THREAD

**Issue by jz5678910** [TheElixZammuto/moonlight-xbox#110] opened 2024-02-04 18:54 UTC
@TheElixZammuto The New retail build 1.15.6.70 is crashing every time I try to select a game from the menu. By crashing I mean it's going back to the Xbox home screen. No error or message of any kind. It gets hung on "Initializing" and then crashes. 

Edit: Something finally popped up, not sure if it's helpful or not 

![PXL_20240204_184712562](https://github.com/TheElixZammuto/moonlight-xbox/assets/38450236/d955b00a-02de-4b8a-83e7-89676847ac03)

![PXL_20240204_184731491 MP](https://github.com/TheElixZammuto/moonlight-xbox/assets/38450236/ad6577b9-a382-44b0-bb41-9f4e6c4253f0)

_Originally posted by @jz5678910 in https://github.com/TheElixZammuto/moonlight-xbox/issues/89#issuecomment-1925874475_

**Comment by jz5678910** [comment] 2024-02-04 19:00
Here's a log from sunshine while it's happening. 
[[20240204135709] Info Trying encode.txt](https://github.com/TheElixZammuto/moonlight-xbox/files/14157962/20240204135709.Info.Trying.encode.txt)

**Comment by TheElixZammuto** [comment] 2024-02-04 19:48
Duplicate of #108

**Closed by TheElixZammuto** 2024-02-04 19:48 UTC
