### ISSUE TITLE
RTSP Handshake failed error 503

### ISSUE THREAD

**Issue by Celteron** [TheElixZammuto/moonlight-xbox#78] opened 2023-05-27 17:11 UTC
If I try to start Desktop or Steam Big Picture from my Xbox One S I get the 503 error in Stage 4. At my Host Big Picture starts, acting like i excpected, but Xbox One S get failure.

Log from Sunshine:
[2023:05:27:18:56:57]: Info: Spawning [steam steam://open/bigpicture] in ["C:\Program Files (x86)\Steam"]
[2023:05:27:18:56:57]: Info: steam steam://open/bigpicture running with PID 8408
[2023:05:27:18:56:57]: Info: Executing [Desktop]

Log from Xbox One S:
Starting RTSP handshake ... Stage 4 started
Reference frame invalidation is not supported by this host
Audio Port: 48000
Video port: 47998
Control port: 47999
RTSP ANNOUNCE request failed: 503
failed: 503
Stage 4 failed with error 503
Cleaning up audio stream...done
Cleaning up platform...done
LiStartConnection 503

Xbox One S
Sunshine Version 0.19.1
Moonlight UWP
TV Resultion 4k

**Tryied different Host Options from 720p to 4k, from 30 fps to 90, from 8k kbps to 85k kbps, reinstallation from Moonlight UWP and Sunshine**

Wired up trough Gbit
On other Clients (Laptop, Phone etc.) working

Host is Windows with 2k Monitor, AMD GPU 6700 XT

If i may help you with further Information, let me know

**Comment by tditheo** [comment] 2023-05-28 20:59
This issue happen to me, and the solution was to use WiFi instead of Ethernet (except if you already use WiFi)

**Comment by TheElixZammuto** [comment] 2023-05-30 09:44
Version 1.13.7 is now live on the store. Do you have different error messages?

**Comment by Celteron** [comment] 2023-05-30 20:11
Dunno how much is nessecary, but last section is where the Service is unavailable and debugging shows the Announce command i get on my Xbox.

**Comment by TheElixZammuto** [comment] 2023-06-10 10:08
Since we already spoke on Discord and we can confirm it does work as intended with v1.13.8, I'm closing this

**Closed by TheElixZammuto** 2023-06-10 10:08 UTC
